
name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request: 
    branches: ['main']
jobs:
  setup: 
    uses: huynhthaianhhd/workflows-actions/.github/workflows/platform-npm-base.yml@main
    secrets: inherit
   

  